#!/bin/sh

fn=ibutton.tar

rm -f $fn
pax -wvf $fn -s ',^,ibutton/,' `tla inventory -s`
pax -wvaf $fn -s ',^mymalloc/,ibutton/mymalloc/,' \
	`tla inventory -s mymalloc`
pax -wvaf $fn -s ',^stringlib/,ibutton/stringlib/,' \
	`tla inventory -s stringlib`
gzip -9v $fn

echo "Tree is `tla logs -f | tail -1`"
